const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const pet = JSON.parse(fs.readFileSync(path.join(root, 'pet/pet.json'), 'utf8'));
assert.equal(pet.spriteVersionNumber, 1);
assert.equal(pet.spritesheetPath, 'spritesheet.png');
assert.ok(pet.displayName.trim());
const png = fs.readFileSync(path.join(root, 'pet', pet.spritesheetPath));
assert.equal(png.subarray(0, 8).toString('hex'), '89504e470d0a1a0a');
assert.equal(png.toString('ascii', 12, 16), 'IHDR');
assert.equal(png.readUInt32BE(16), 1536);
assert.equal(png.readUInt32BE(20), 1872);
assert.equal(png[25], 6, 'Expected RGBA PNG');
const preview = fs.readFileSync(path.join(root, 'preview.html'), 'utf8');
assert.ok(preview.includes('pet/spritesheet.png'));
assert.ok(!preview.includes('file:///') && !preview.includes('C:/Users/'));
console.log('OK: pet manifest, RGBA PNG, 1536x1872 grid, portable preview reference.');
console.log('Visual animation quality and client state triggers require separate inspection.');
